import {
  Bot,
  ArrowRight,
  ArrowUpRight,
  Play,
  ChevronDown,
  Linkedin,
  Instagram,
  Github,
  Youtube,
  Menu,
  X,
  Sparkles,
  Rocket,
  Users,
  Target,
  Layers,
  Cog,
  Cpu,
  Code2,
  Code,
  FlaskConical,
  Briefcase,
  Megaphone,
  Mail,
  MapPin,
  Calendar,
  Send,
  Gamepad2,
  PenTool,
  Bug,
  Shield,
  Orbit,
  Award,
  Download,
  Heart,
  Plane,
  Package,
  Wrench,
  Share2,
  TrendingUp,
  MessageCircle,
  HelpCircle,
} from "lucide-react";

// Explicit map (tree-shakeable) so content data can reference icons by name.
const map = {
  bot: Bot,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  play: Play,
  "chevron-down": ChevronDown,
  linkedin: Linkedin,
  instagram: Instagram,
  github: Github,
  youtube: Youtube,
  menu: Menu,
  x: X,
  sparkles: Sparkles,
  rocket: Rocket,
  users: Users,
  target: Target,
  layers: Layers,
  cog: Cog,
  cpu: Cpu,
  "code-2": Code2,
  code: Code,
  "flask-conical": FlaskConical,
  briefcase: Briefcase,
  megaphone: Megaphone,
  mail: Mail,
  "map-pin": MapPin,
  calendar: Calendar,
  send: Send,
  "gamepad-2": Gamepad2,
  "pen-tool": PenTool,
  bug: Bug,
  shield: Shield,
  orbit: Orbit,
  award: Award,
  download: Download,
  heart: Heart,
  plane: Plane,
  package: Package,
  wrench: Wrench,
  "share-2": Share2,
  "trending-up": TrendingUp,
  "message-circle": MessageCircle,
};

export default function Icon({ name, className = "", ...props }) {
  const Cmp = map[name] ?? HelpCircle;
  return <Cmp className={className} {...props} />;
}
